<?php
/**
 * Package path rules.
 *
 * @package SelectiveEntitySync
 */

namespace SelectiveEntitySync\Manifest;

/**
 * Validates the relative paths of files stored inside a package.
 *
 * Paths are generated by the exporter, so the allowed format is deliberately
 * strict: relative, forward slashes, a safe character set, no "." or ".."
 * segments. This is what makes extraction safe from path traversal (zip-slip).
 */
final class PackagePath {

	/**
	 * Name of the manifest file at the root of a package.
	 */
	public const MANIFEST_FILE = 'manifest.json';

	/**
	 * Maximum length of a package path.
	 */
	public const MAX_LENGTH = 255;

	/**
	 * Maximum number of path segments.
	 */
	public const MAX_DEPTH = 8;

	/**
	 * Whether a path is a valid location for a package file.
	 *
	 * @param string $path Relative path inside the package.
	 * @return bool
	 */
	public static function is_valid( string $path ): bool {
		if ( '' === $path || strlen( $path ) > self::MAX_LENGTH || self::MANIFEST_FILE === $path ) {
			return false;
		}

		$segments = explode( '/', $path );
		if ( count( $segments ) > self::MAX_DEPTH ) {
			return false;
		}

		foreach ( $segments as $segment ) {
			if ( '' === $segment || '.' === $segment || '..' === $segment ) {
				return false;
			}
			if ( 1 !== preg_match( '/^[A-Za-z0-9._-]+$/D', $segment ) ) {
				return false;
			}
		}

		return true;
	}
}
